<?php
// Automatically Generated by TestLink Installer - Mon, 24 Jul 17 15:19:07 +0200
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', '123456');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
